@startuml

participant Client
participant Seller
participant Bank
participant Exchange

Client -> Bank : Create Account: ID<sub>C</sub>, ID<sub>B</sub>, T, Sign<sub>C</sub>(ID<sub>C</sub>, ID<sub>B</sub>, T), Cert<sub>C</sub>
Seller -> Bank : Create Account: ID<sub>S</sub>, ID<sub>B</sub>, T, Sign<sub>C</sub>(ID<sub>S</sub>, ID<sub>B</sub>, T), Cert<sub>S</sub>

Client -> Seller : Buy: ID<sub>C</sub>, ID<sub>S</sub>, T, Sign<sub>C</sub>(ID<sub>C</sub>, ID<sub>S</sub>, T), Cert<sub>C</sub>
Seller -> Client : ID<sub>Payment</sub>

Client -> Bank : ID<sub>C</sub>, ID<sub>B</sub>, T, Sign<sub>C</sub>(ID<sub>C</sub>, ID<sub>B</sub>, T), ID<sub>Payment</sub>
Bank -> Exchange : Exchange : ID<sub>B</sub>, ID<sub>BC</sub>, T, Sign<sub>B</sub>(ID<sub>B</sub>, ID<sub>BC</sub>, T), Cert<sub>B</sub>, Amount, ID<sub>C</sub>, Sign<sub>B</sub>(Amount, ID<sub>C</sub>)
Client -> Exchange: Delegate: ID<sub>C</sub>, Cert<sub>C</sub>, ID<sub>B</sub>, Policy, Sign<sub>C</sub>([ID<sub>B</sub>, Policy])

Bank -> Seller : Inform: ID<sub>B</sub>, ID<sub>S</sub>, T, SignB(ID<sub>B</sub>, ID<sub>S</sub>, T), Cert<sub>B</sub>
Seller -> Bank : Approve: ID<sub>S</sub>, ID<sub>B</sub>, T, Sign<sub>C</sub>(ID<sub>S</sub>, ID<sub>B</sub>, T),

@enduml